---
- hosts: all
  become: true
  tasks:

  - name: Collec Log File
    find:
      paths: /var/log
      patterns: '*.log'
    register: log_files

  - name: Copy logs
    fetch:
      src: "{{ item.path }}"
      dest: /tmp/logs/
      flat: yes
    with_items: "{{ log_files.files}}"
